repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [extract, lambda/stream_unzip_s3.py, tests/airbnb, tests/include]
        pass_filenames: false
      - id: ruff-format
        args: [extract, lambda/stream_unzip_s3.py, tests/airbnb, tests/include]
        pass_filenames: false
